export const cadastrosExemplo = [
  {
    id: 1,
    tipo: "ORGANIZADOR",
    nome: "Ana Beatriz Souza",
    email: "ana.souza@email.com",
    telefone: "(11) 99999-1111",
    cidade: "São Paulo",
    estado: "SP",
    criado_em: "2026-08-22",
    status: "PENDENTE",
    eventos_cadastrados: 3,
  },
  {
    id: 2,
    tipo: "FORNECEDOR",
    nome: "Buffet Sabor & Arte",
    razao_social: "Sabor & Arte Eventos LTDA",
    cnpj: "12.345.678/0001-90",
    categoria_atuacao: "Buffet e Gastronomia",
    email: "contato@saborarte.com",
    telefone: "(11) 98888-2222",
    cidade: "São Paulo",
    estado: "SP",
    regiao_atendimento: "São Paulo e região",
    descricao:
      "Serviço de buffet para casamentos, festas e eventos corporativos.",
    site: "https://www.saborarte.com",
    criado_em: "2026-08-23",
    status: "PENDENTE",
  },
  {
    id: 3,
    tipo: "ORGANIZADOR",
    nome: "Carlos Menezes",
    email: "carlos.menezes@email.com",
    telefone: "(11) 97777-3333",
    cidade: "Campinas",
    estado: "SP",
    criado_em: "2026-08-24",
    status: "PENDENTE",
    eventos_cadastrados: 1,
  },
  {
    id: 4,
    tipo: "FORNECEDOR",
    nome: "Som & Luz Eventos",
    razao_social: "Som & Luz Produções LTDA",
    cnpj: "23.456.789/0001-01",
    categoria_atuacao: "Som e Iluminação",
    email: "contato@somluz.com",
    telefone: "(11) 96666-4444",
    cidade: "São Paulo",
    estado: "SP",
    regiao_atendimento: "Grande São Paulo",
    descricao: "Equipamentos de som, iluminação e estrutura para eventos.",
    site: "https://www.somluz.com",
    criado_em: "2026-08-20",
    status: "APROVADO",
    analisado_por_nome: "Administrador",
    data_analise: "2026-08-20T14:30:00",
  },
  {
    id: 5,
    tipo: "FORNECEDOR",
    nome: "Espaço Verde Locações",
    razao_social: "Espaço Verde Eventos LTDA",
    cnpj: "34.567.890/0001-12",
    categoria_atuacao: "Espaços para eventos",
    email: "espacoverde@email.com",
    telefone: "(11) 95555-5555",
    cidade: "Osasco",
    estado: "SP",
    regiao_atendimento: "Grande São Paulo",
    descricao: "Locação de espaço e estrutura para eventos.",
    site: "",
    criado_em: "2026-08-19",
    status: "REJEITADO",
    analisado_por_nome: "Administrador",
    data_analise: "2026-08-19T10:15:00",
    motivo_rejeicao: "Documentação incompleta.",
  },
  {
    id: 6,
    tipo: "FORNECEDOR",
    nome: "Lumi Decor",
    cnpj: "45.678.901/0001-23",
    categoria_atuacao: "Decoração",
    email: "contato@lumidecor.com",
    criado_em: "2026-09-21",
    status: "PENDENTE",
  },
  {
    id: 7,
    tipo: "ORGANIZADOR",
    nome: "Marina Alves",
    email: "marina@email.com",
    criado_em: "2026-09-20",
    status: "PENDENTE",
  },
  {
    id: 8,
    tipo: "FORNECEDOR",
    nome: "SafeFest Segurança",
    categoria_atuacao: "Segurança",
    email: "oi@safefest.com",
    criado_em: "2026-09-19",
    status: "PENDENTE",
  },
];